language: node_js
node_js:
  - "node"
cache: npm
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: dist
  on:
    branch: main
